server:
  port: 8080

spring:
  # H2 Connection
  h2:
    console:
      enabled: true # Enabling H2 Console
      path: /h2-console
  datasource:
    url: jdbc:h2:file:~/dio;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS access_control_api
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      show-sql: true
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: update
    properties:
      org:
        hibernate:
          envers:
            default_schema: access_control_api