server:
  port: 8081

spring:
  # H2 Connection
  h2:
    console:
      enabled: true # Enabling H2 Console
      path: /h2-console
  datasource:
    url: jdbc:h2:~/petdio;INIT=RUNSCRIPT FROM 'classpath:init.sql';DB_CLOSE_ON_EXIT=FALSE;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create
      type: TRACE
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect