
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Djeymisson/santander-fullstack-developer
          searchPaths: 'spring-cloud/config-repo'