#DEV Environment

app:
  message: "Hi, mom, I'm home (Development)!"

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
